management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus # enables /actuator/prometheus endpoint
          - health # enables /actuator/health endpoint
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always